<?php

namespace AppBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function userNotifications($user) {
        $query = $this->_em->createQueryBuilder()->select("u")->from('AppBundle:Notification','u')->where('u.user=:user')
            ->setParameter(':user', $user)->orderBy('u.date', 'DESC')->getQuery();
        $user_notifications = $query->getResult();
        return $user_notifications;
    }

    public function notificationsSorted() {
        $query = $this->_em->createQueryBuilder()->select("u")->from('AppBundle:Notification','u')->orderBy('u.date', 'DESC')->getQuery();
        $notifications = $query->getResult();
        return $notifications;
    }
}