<?php

namespace AppBundle\Repository;

/**
 * Voivodeship_city
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Voivodeship_city extends \Doctrine\ORM\EntityRepository
{
    public function findCitiesByVoivodeship($voivodeship_id) {
        $em = $this->getDoctrine()->getManager();
        $city_names = [];
        $query = $em->createQueryBuilder()->select('c.name')->from('AppBundle:City','c')->where('c.voivodeship=:id')->setParameter(':id', $_POST['voivodeship_id'])->getQuery();
        $voivodeship_names = $query->getResult();
        foreach ($voivodeship_names as $city) {
            $city_names[] = $city['name'];
        }
        return $city_names;
    }
}
